"""training routine library

Revision ID: 5a1284d716f8
Revises: f3a1c9d2e8b4
Create Date: 2026-08-17 09:16:16.968659
"""
import sqlalchemy as sa
from alembic import op

revision = '5a1284d716f8'
down_revision = 'f3a1c9d2e8b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sport', sa.String(length=40), nullable=False),
    sa.Column('sequence_key', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'sequence_key', name='uq_routine_sport_sequence')
    )
    op.create_table('routine_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('fighter_label', sa.String(length=4), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['training_routines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'routine_id', 'fighter_label', name='uq_routine_hit')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_hits')
    op.drop_table('training_routines')
    # ### end Alembic commands ###
