"""baseline schema

Mirrors the schema ``Base.metadata.create_all()`` has always produced (no
Alembic revision existed before this one). Deliberately excludes the
``uq_session_fighter``/``uq_session_label`` constraints on ``session_fighters``
so pre-existing dev databases can be stamped at this revision and then
migrated forward through the next one, which deduplicates any existing rows
before adding those constraints.

Revision ID: b566b42839c9
Revises:
Create Date: 2026-08-17 06:49:19.327638
"""
import sqlalchemy as sa
from alembic import op

revision = 'b566b42839c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('calibrated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('fighter_label', sa.String(length=4), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_fighter_label'), 'events', ['fighter_label'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_fighters')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_fighter_label'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_table('sessions')
    op.drop_table('fighters')
    # ### end Alembic commands ###
